<?php
if (!function_exists('getBlogArticles')) {
    function getBlogArticles()
    {
        return [
            'hipertensao' => [
                'title' => 'Hipertensão arterial: o que ela faz com o corpo',
                'date' => 'Atualizado em 2026 • 8 min',
                'summary' => 'A pressão alta aumenta o esforço do coração e pode danificar artérias, rins, cérebro e olhos quando não é controlada.',
                'content' => '<p>A hipertensão arterial é a elevação persistente da pressão do sangue dentro das artérias. Ela geralmente é silenciosa, e por isso é chamada de “assassina silenciosa”: muitas pessoas não sentem sintomas, mas os danos acontecem ao longo do tempo.</p><h3>O que ela faz no corpo</h3><p>Com a pressão elevada, as artérias ficam mais rígidas e menos elásticas. O coração passa a bater com mais força para empurrar o sangue, o que pode levar ao aumento do músculo cardíaco, risco de insuficiência cardíaca, AVC, doença renal e prejuízo visual.</p><h3>Como ela se manifesta</h3><p>Nem sempre há sintomas. Em alguns casos, pode haver dor de cabeça, tontura, palpitações, zumbido, visão turva ou sensação de pressão no peito. Mesmo sem queixas, a pressão elevada pode estar provocando lesões no organismo.</p><h3>Como melhorar a qualidade de vida</h3><p>Controle a pressão com acompanhamento médico, reduza o sal, prefira alimentos naturais, mantenha atividade física orientada, evite álcool em excesso e acompanhe a medição da pressão em casa. O uso correto dos medicamentos também é essencial para evitar complicações.</p><h3>Quando procurar ajuda</h3><p>Procure atendimento rápido se houver dor no peito, falta de ar intensa, fraqueza de um lado do corpo, confusão mental, desmaio ou pressão muito alta com sintomas.</p><div style="margin-top:20px; padding:18px; background:#f8fafc; border-left:4px solid #851e32; border-radius:10px;"><h3 style="margin-top:0; color:#851e32;">Tradução</h3><p>Em outras palavras, a pressão alta não “só eleva a leitura do aparelho”. Ela força o coração e os vasos sanguíneos a trabalhar mais do que deveriam, e isso pode desgastar o corpo aos poucos. Quando a pessoa cuida da alimentação, toma os remédios corretamente e acompanha a pressão, reduz muito o risco de problemas graves.</p></div>'
            ],
            'insuficiencia' => [
                'title' => 'Insuficiência cardíaca: o que acontece com o coração',
                'date' => 'Atualizado em 2026 • 9 min',
                'summary' => 'O coração continua funcionando, mas não consegue suprir a demanda do corpo com a mesma eficiência, e isso pode causar cansaço e inchaço.',
                'content' => '<p>Insuficiência cardíaca não significa que o coração parou. Ela significa que ele está trabalhando menos bem para bombear sangue e atender às necessidades do corpo. Isso pode acontecer por hipertensão, doença arterial, alterações das válvulas, arritmias ou problemas prévios do músculo cardíaco.</p><h3>Como a doença afeta o corpo</h3><p>Quando o bombeamento fica menos eficiente, o sangue pode se acumular em alguns setores. Isso leva à sensação de falta de ar, cansaço, edema nas pernas, ganho rápido de peso, dificuldade para caminhar e piora ao deitar.</p><h3>O que acontece no coração</h3><p>O coração tenta compensar com mais esforço. Com o tempo, ele pode aumentar de tamanho, a pressão no interior das câmaras sobe e aumenta a retenção de líquido. Por isso, o paciente pode ter piora progressiva da tolerância a atividades e limitação no dia a dia.</p><h3>Como viver melhor</h3><p>É fundamental seguir a medicação prescrita, controlar o sal, pesar-se diariamente, observar ganho de peso rápido, manter a hidratação adequada conforme orientação médica e não interromper remédios sem discutir com o médico. O acompanhamento regular ajuda a prevenir descompensações.</p><h3>Quando procurar ajuda</h3><p>Se houver falta de ar em repouso, escurecimento da visão, confusão, inchaço importante nas pernas, aumento rápido de peso ou piora repentina, é importante buscar avaliação médica.</p><div style="margin-top:20px; padding:18px; background:#f8fafc; border-left:4px solid #851e32; border-radius:10px;"><h3 style="margin-top:0; color:#851e32;">Tradução</h3><p>O coração continua vivo e trabalhando, mas está com menos capacidade de bombear sangue adequadamente. Como resultado, o corpo guarda líquido e o paciente ganha cansaço e falta de ar. Com tratamento, controle de sal e acompanhamento, muitas pessoas conseguem viver melhor e com menos sintomas.</p></div>'
            ],
            'arritmia' => [
                'title' => 'Arritmias: quando o ritmo do coração muda',
                'date' => 'Atualizado em 2026 • 7 min',
                'summary' => 'A alteração no ritmo pode causar palpitações, tonturas e sensação de “coração acelerado” ou irregular.',
                'content' => '<p>Arritmias são alterações na formação ou na condução do impulso elétrico que coordena os batimentos do coração. Elas podem ser causadas por ansiedade, excesso de cafeína, alterações do sistema nervoso, doenças da tireoide, uso de certos medicamentos, hipertensão, insuficiência cardíaca ou problemas estruturais do coração.</p><h3>O que acontece</h3><p>Em vez de bater de forma regular, o coração pode acelerar, desacelerar ou ficar irregular. Isso pode reduzir o débito cardíaco, interferir na oxigenação do corpo e, em algumas situações, aumentar o risco de formação de coágulos ou de desmaios.</p><h3>Sinais que não devem ser ignorados</h3><p>Palpitações, sensação de coração “pulando”, tontura, desmaio, falta de ar, dor no peito ou mal-estar intenso precisam de avaliação. O eletrocardiograma, o Holter e outros exames ajudam a entender qual é o tipo da arritmia.</p><h3>Como viver melhor</h3><p>Evite cafeína, energia ou suplementos sem orientação, não use remédios sem indicação, registre os episódios e o momento em que ocorreram, e mantenha acompanhamento com o cardiologista. Em casos mais graves, o tratamento pode incluir medicamentos ou procedimentos específicos.</p><div style="margin-top:20px; padding:18px; background:#f8fafc; border-left:4px solid #851e32; border-radius:10px;"><h3 style="margin-top:0; color:#851e32;">Tradução</h3><p>O sinal elétrico do coração fica desregulado e o ritmo deixa de ser estável. Isso pode fazer o coração bater rápido, irregular ou se sentir estranho. Quando isso acontece com frequência, é preciso investigar para evitar riscos e melhorar o bem-estar.</p></div>'
            ],
            'colesterol' => [
                'title' => 'Colesterol e placas nas artérias',
                'date' => 'Atualizado em 2026 • 6 min',
                'summary' => 'O excesso de gordura no sangue favorece a formação de placas que podem estreitar e bloquear as artérias.',
                'content' => '<p>O colesterol é essencial para o corpo, mas quando está em excesso, especialmente o LDL, ele pode se acumular na parede das artérias. Esse processo é chamado de aterosclerose e pode fazer os vasos ficarem mais estreitos e menos maleáveis.</p><h3>Como isso afeta o coração</h3><p>Se as artérias do coração ficam obstruídas, o fluxo de sangue pode diminuir. Isso aumenta o risco de angina, infarto e AVC. A piora não costuma acontecer de uma hora para outra: é um processo gradual que pode ser lento e silencioso.</p><h3>Como melhorar</h3><p>Uma alimentação com menos alimentos ultraprocessados, menos sal e menos gordura saturada ajuda muito. Frutas, legumes, grãos integrais e gorduras de boa qualidade são importantes. A atividade física regular, a perda de peso quando indicada e a adesão à medicação também auxiliam no controle.</p><h3>O papel do médico</h3><p>Nem todo paciente precisa da mesma meta. O objetivo depende do risco cardiovascular individual, do histórico, da idade e de outras condições. O controle do colesterol deve ser acompanhado com exames e orientação individualizada.</p><div style="margin-top:20px; padding:18px; background:#f8fafc; border-left:4px solid #851e32; border-radius:10px;"><h3 style="margin-top:0; color:#851e32;">Tradução</h3><p>O colesterol alto não é apenas um “número do exame”; ele pode formar acúmulo dentro dos vasos e prejudicar o fluxo sanguíneo. Quando a pessoa muda hábitos e segue a orientação médica, o risco de problemas cardíacos tende a cair.</p></div>'
            ],
            'exames' => [
                'title' => 'Como interpretar os exames cardiológicos',
                'date' => 'Atualizado em 2026 • 8 min',
                'summary' => 'Os exames ajudam a entender a estrutura, a função e o ritmo do coração, mas o resultado deve ser visto no contexto do paciente.',
                'content' => '<p>Os exames cardiológicos ajudam a responder perguntas importantes: o coração está batendo em ritmo adequado? Ele está bombeando bem? Há alteração no músculo, nas válvulas ou na circulação? O laudo deve ser lido junto com os sintomas, histórico e exame físico.</p><h3>Exames mais comuns</h3><p>O eletrocardiograma mostra a atividade elétrica do coração. O ecocardiograma avalia estrutura, válvulas e função de bombeamento. O Holter registra o ritmo durante um período maior e ajuda a encontrar alterações intermitentes. Os exames laboratoriais medem colesterol, glicose, função renal e outros fatores que influenciam o coração.</p><h3>O que o médico considera</h3><p>Um exame normal não descarta completamente um problema e um exame alterado nem sempre significa doença grave. O contexto é o que orienta a decisão. Sempre que houver dúvida, o resultado precisa ser discutido com o profissional que acompanha o caso.</p><h3>Como usar essa informação</h3><p>Use o laudo para entender o que foi avaliado, mas não para se assustar sozinho ou buscar diagnóstico sem orientação. O papel do médico é conectar os exames aos sintomas, à rotina e ao risco individual.</p><div style="margin-top:20px; padding:18px; background:#f8fafc; border-left:4px solid #851e32; border-radius:10px;"><h3 style="margin-top:0; color:#851e32;">Tradução</h3><p>Os exames são uma fotografia do coração em determinado momento, não uma sentença isolada. Eles ajudam a ver o que está acontecendo com o ritmo e a função do coração, mas os médicos usam o conjunto de informações para decidir o melhor cuidado.</p></div>'
            ]
        ];
    }
}

?>
