<?php
function getInformacoesHtml() {
    return <<<HTML
                <div class="info-card"><h3><i class="fas fa-info-circle"></i> Sobre o CardioWeb</h3><p>O CardioWeb é uma plataforma digital criada para ajudar pacientes a acompanharem sua saúde cardiológica com mais facilidade, organização e segurança.</p><p>Por meio do painel, o usuário consegue visualizar informações importantes, consultar conteúdos, agendar atendimentos e acompanhar exames em um único lugar.</p></div>
                <div class="info-card"><h3><i class="fas fa-question-circle"></i> Para que serve este site?</h3><p>O site serve para centralizar o cuidado com a saúde do coração, reunindo ferramentas simples e acessíveis para o paciente e também para a equipe administrativa.</p><p>Ele facilita o dia a dia, trazendo mais praticidade para consultas, exames e comunicação com a clínica.</p></div>
                <div class="info-card"><h3><i class="fas fa-chart-line"></i> Como o site funciona</h3><div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 15px;"><div style="padding: 15px; background: #fdf0ec; border-radius: 12px;"><i class="fas fa-calendar-check" style="color: #8b2a3e; font-size: 24px;"></i><div style="font-weight: 600; margin-top: 10px;">Agendamento</div><div style="font-size: 12px; color: #8a7569;">O usuário pode solicitar consultas e acompanhar novos pedidos.</div></div><div style="padding: 15px; background: #fdf0ec; border-radius: 12px;"><i class="fas fa-file-alt" style="color: #8b2a3e; font-size: 24px;"></i><div style="font-weight: 600; margin-top: 10px;">Exames</div><div style="font-size: 12px; color: #8a7569;">Os exames ficam organizados para consulta rápida e visualização clara.</div></div><div style="padding: 15px; background: #fdf0ec; border-radius: 12px;"><i class="fas fa-newspaper" style="color: #8b2a3e; font-size: 24px;"></i><div style="font-weight: 600; margin-top: 10px;">Informações</div><div style="font-size: 12px; color: #8a7569;">O blog traz conteúdos úteis sobre prevenção, sintomas e cuidados com a saúde.</div></div></div></div>
                <div class="info-card"><h3><i class="fas fa-shield-alt"></i> Segurança e privacidade</h3><p>Seus dados são protegidos e a plataforma segue boas práticas de organização e controle de acesso para garantir mais confiança ao usuário.</p></div>
HTML;
}
